# Generated by Django 4.2 on 2023-05-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0005_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="ngo",
            name="social",
            field=models.CharField(default="www.instagram.com", max_length=100),
        ),
        migrations.AddField(
            model_name="ngo",
            name="website",
            field=models.CharField(
                default="https://www.akshayapatra.org/", max_length=100
            ),
        ),
    ]
