# Generated by Django 4.2 on 2023-05-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0006_ngo_social_ngo_website"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restraunts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("r_name", models.CharField(max_length=100)),
                ("r_location", models.CharField(max_length=100)),
                ("r_contact", models.CharField(max_length=10)),
                ("average_food", models.IntegerField()),
                ("ngolat", models.FloatField(blank=True, null=True)),
                ("ngolong", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
