# Generated by Django 4.2 on 2023-05-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0007_restraunts"),
    ]

    operations = [
        migrations.AddField(
            model_name="restraunts",
            name="approx_people",
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
