# Generated by Django 4.2 on 2023-05-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0008_restraunts_approx_people"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ngo",
            name="social",
            field=models.CharField(
                default="https://www.instagram.com/", max_length=100
            ),
        ),
    ]
