# Generated by Django 4.2 on 2023-05-01 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0002_ngo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ngo", old_name="ngo_lat", new_name="ngolat",
        ),
        migrations.RenameField(
            model_name="ngo", old_name="ngo_long", new_name="ngolong",
        ),
    ]
