# Generated by Django 4.2 on 2023-05-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0003_rename_ngo_lat_ngo_ngolat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ngo",
            name="Contact",
            field=models.CharField(default="12345678", max_length=10),
        ),
    ]
